Lab3
Sdude225/PAM_LAB pull request #4
Opened 2021-04-23 07:29 UTC by Sdude225

Bottom tabs, didn't found API based on online courses, so used one which searches for available job positions. Coroutines, bottom tabs, small ui fixes

2021-04-25 23:03 UTC, ASV44 requested changes
@Sdude225 Add `app/build` directory to git ignore and clean up project version control

2021-04-26 16:22 UTC, Sdude225 commented
@ASV44 Done

2021-04-27 21:52 UTC, ASV44 requested changes
@Sdude225 You have conflicts. Rebase current branch and force push after that

2021-04-27 21:52 UTC, ASV44 commented on app/src/main/java/com/sample/app/feed/FeedActivity.kt
> +//    }
Remove commented code. It does nothing and there is no reason to keep it

2021-05-13 13:24 UTC, merged